### PR TITLE
Nsspi target framework changed to .NetStandard2.0

### PR DESCRIPTION
**Pull request by StefanOssendorf**
Nsspi targets now .NetStandard2.0
Other projects now targets .net4 .6.1
Nuspec file removed and nuget file will now be created on each build (new capaibility of VS17 used for that)
Assemblyinfo resieds now within csproj of nsspi project
ReSharpher folder added to gitignore

Please update the version after merge (I suggest v3.0) and publish a new nuget package :-). Thanks!

### CODE REVIEW

**Comment by antiduh** [comment]
Well damn, thanks. I'll get to this this weekend.

**Comment by StefanOssendorf** [comment]
You're welcome :-).
The Nsspi-Lib now multi targets .Net 4.0 and .NetStandard2.0 for better backward compability.

**Comment by StefanOssendorf** [comment]
Hey, any news for this?

Cheers

**Comment by antiduh** [comment]
Hi, i'm a little behind due to illness. I'll see if I can get to this sometime this week. Sorry for the delay!

**Comment by StefanOssendorf** [comment]
Hey, all fine! Health goes First :). Get Well!

Kevin Thompson <notifications@github.com> schrieb am Mo., 10. Juni 2019,
20:14:

**Comment by antiduh** [comment]
Hey Stefan, I like the changes, expertly done. Sorry it took me so long to get to it, I also wanted to spend a little time familiarizing myself with multi-targeting. I'll admit, I've not worked with the SDK project file format, .Net Core, or multi-targeting much yet.

**Comment by StefanOssendorf** [comment]
No problem :-). We all have stuff to do.
Yeah multitargeting is now luckily much much easier than before with the new csproj format but I don't get all the details. E.g. ` <TargetFrameworks>netstandard2.0;net40</TargetFrameworks>` switch the values to ` <TargetFrameworks>net40;netstandard2.0</TargetFrameworks>` and it won't compile. Microsoft knows which magic is at work :-D.

I can recommend using the new project file format. I find it so much cleaner and easier to use than the old.

Ps: Can you provide a an updated nuget-package with v0.3.0? Would love to use that at work to get rid of some warnings :-D

**Comment by antiduh** [comment]
Yep, i'm updating some docs now and I'll post a new build. Cheers!

**Comment by antiduh** [comment]
All set and published. Thanks again!

**Comment by StefanOssendorf** [comment]
Thank you and have a good week :-)

**Pull request merged**
